// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using LiRAWebApi.Models;
//
//    var tripNotification = TripNotification.FromJson(jsonString);

namespace LiRACore.Models.RawData
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

  
    //[BindProperties(SupportsGet = true)]
    public partial class TripNotification 
    {
        [BindProperty]
        [JsonProperty("task_id")]
        public long TaskId { get; set; }

        [BindProperty]
        [JsonProperty("timestamp_utc")]
        public DateTimeOffset TimestampUtc { get; set; }

        [BindProperty]
        [JsonProperty("trip_end_time_utc")]
        public DateTimeOffset TripEndTimeUtc { get; set; }

        [BindProperty]
        [JsonProperty("trip_id")]
        public Guid TripId { get; set; }
    }

    public partial class TripNotification
    {
        public static TripNotification FromJson(string json) => JsonConvert.DeserializeObject<TripNotification>(json, LiRAWebApi.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TripNotification self) => JsonConvert.SerializeObject(self, LiRAWebApi.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}