using System;
using System.Collections.Generic;
using System.Text;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using LiRACore.Models;
//
//    var autoPiSensor = AutoPiSensor.FromJson(jsonString);

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using LiRACore.Models;
//
//    var autoPiSensor = AutoPiSensor.FromJson(jsonString);

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using LiRACore.Models;
//
//    var autoPiSensor = AutoPiSensor.FromJson(jsonString);

namespace LiRACore.Models.RawData
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.IO;
    using LiRACore.Helpers;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AutoPi_Json
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("@vid", NullValueHandling = NullValueHandling.Ignore)]
        public long? Vid { get; set; }

        [JsonProperty("event.system.time.old", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? EventSystemTimeOld { get; set; }
        [JsonProperty("start_time_utc", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset StartTimeUtc { get; set; }

        [JsonProperty("end_time_utc", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset EndTimeUtc { get; set; }

        [JsonProperty("start_position_lat", NullValueHandling = NullValueHandling.Ignore)]
        public string StartPositionLat { get; set; }

        [JsonProperty("start_position_lng", NullValueHandling = NullValueHandling.Ignore)]
        public string StartPositionLng { get; set; }

        [JsonProperty("start_position_display", NullValueHandling = NullValueHandling.Ignore)]
        public PositionDisplay StartPositionDisplay { get; set; }

        [JsonProperty("end_position_lat", NullValueHandling = NullValueHandling.Ignore)]
        public string EndPositionLat { get; set; }

        [JsonProperty("end_position_lng", NullValueHandling = NullValueHandling.Ignore)]
        public string EndPositionLng { get; set; }

        [JsonProperty("end_position_display", NullValueHandling = NullValueHandling.Ignore)]
        public PositionDisplay EndPositionDisplay { get; set; }

        [JsonProperty("device", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Device { get; set; }

        [JsonProperty("duration", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? Duration { get; set; }

        [JsonProperty("distanceKm", NullValueHandling = NullValueHandling.Ignore)]
        public double? DistanceKm { get; set; }

        [JsonProperty("@tag", NullValueHandling = NullValueHandling.Ignore)]
        public string Tag { get; set; }

        [JsonProperty("@t", NullValueHandling = NullValueHandling.Ignore)]
        public string T { get; set; }

        [JsonProperty("event.system.time.source", NullValueHandling = NullValueHandling.Ignore)]
        public string EventSystemTimeSource { get; set; }

        [JsonProperty("@ts", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset Ts { get; set; }

        [JsonProperty("@uid", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Uid { get; set; }


        [JsonProperty("@rec", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? Rec { get; set; }

        [JsonProperty("event.system.time.new", NullValueHandling = NullValueHandling.Ignore)]
        public string EventSystemTimeNew { get; set; }

        [JsonProperty("event.system.power.trigger", NullValueHandling = NullValueHandling.Ignore)]
        public string EventSystemPowerTrigger { get; set; }

        [JsonProperty("acc.xyz.z", NullValueHandling = NullValueHandling.Ignore)]
        public double? AccXyzZ { get; set; }

        [JsonProperty("acc.xyz.y", NullValueHandling = NullValueHandling.Ignore)]
        public double? AccXyzY { get; set; }

        [JsonProperty("acc.xyz.x", NullValueHandling = NullValueHandling.Ignore)]
        public double? AccXyzX { get; set; }

        [JsonProperty("event.vehicle.obd.protocol", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? EventVehicleObdProtocol { get; set; }

        [JsonProperty("event.vehicle.obd.autodetected", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EventVehicleObdAutodetected { get; set; }

        [JsonProperty("obd.bat.voltage", NullValueHandling = NullValueHandling.Ignore)]
        public double? ObdBatVoltage { get; set; }

        [JsonProperty("obd.bat.state", NullValueHandling = NullValueHandling.Ignore)]
        public string ObdBatState { get; set; }

        [JsonProperty("obd.bat.level", NullValueHandling = NullValueHandling.Ignore)]
        public long? ObdBatLevel { get; set; }

        [JsonProperty("obd.speed.value", NullValueHandling = NullValueHandling.Ignore)]
        public long? ObdSpeedValue { get; set; }

        [JsonProperty("obd.speed.unit", NullValueHandling = NullValueHandling.Ignore)]
        public string ObdSpeedUnit { get; set; }

        [JsonProperty("obd.rpm.unit", NullValueHandling = NullValueHandling.Ignore)]
        public string ObdRpmUnit { get; set; }

        [JsonProperty("obd.rpm.value", NullValueHandling = NullValueHandling.Ignore)]
        public double? ObdRpmValue { get; set; }

        [JsonProperty("obd.engine_load.unit", NullValueHandling = NullValueHandling.Ignore)]
        public string ObdEngineLoadUnit { get; set; }

        [JsonProperty("obd.engine_load.value", NullValueHandling = NullValueHandling.Ignore)]
        public double? ObdEngineLoadValue { get; set; }

        [JsonProperty("obd.coolant_temp.value", NullValueHandling = NullValueHandling.Ignore)]
        public long? ObdCoolantTempValue { get; set; }

        [JsonProperty("obd.coolant_temp.unit", NullValueHandling = NullValueHandling.Ignore)]
        public string ObdCoolantTempUnit { get; set; }

        [JsonProperty("obd.intake_temp.value", NullValueHandling = NullValueHandling.Ignore)]
        public long? ObdIntakeTempValue { get; set; }

        [JsonProperty("obd.intake_temp.unit", NullValueHandling = NullValueHandling.Ignore)]
        public string ObdIntakeTempUnit { get; set; }

        [JsonProperty("obd.ambiant_air_temp.value", NullValueHandling = NullValueHandling.Ignore)]
        public long? ObdAmbiantAirTempValue { get; set; }

        [JsonProperty("obd.ambiant_air_temp.unit", NullValueHandling = NullValueHandling.Ignore)]
        public string ObdAmbiantAirTempUnit { get; set; }

        [JsonProperty("rpi.temp.cpu", NullValueHandling = NullValueHandling.Ignore)]
        public RpiTemp RpiTempCpu { get; set; }

        [JsonProperty("rpi.temp.gpu", NullValueHandling = NullValueHandling.Ignore)]
        public RpiTemp RpiTempGpu { get; set; }

        [JsonProperty("track.pos.utc", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? TrackPosUtc { get; set; }

        [JsonProperty("track.pos.cog", NullValueHandling = NullValueHandling.Ignore)]
        public double? TrackPosCog { get; set; }

        [JsonProperty("track.pos.nsat", NullValueHandling = NullValueHandling.Ignore)]
        public long? TrackPosNsat { get; set; }

        [JsonProperty("track.pos.alt", NullValueHandling = NullValueHandling.Ignore)]
        public double? TrackPosAlt { get; set; }

        [JsonProperty("track.pos.sog", NullValueHandling = NullValueHandling.Ignore)]
        public double? TrackPosSog { get; set; }

        [JsonProperty("track.pos.loc", NullValueHandling = NullValueHandling.Ignore)]
        public TrackPosLoc TrackPosLoc { get; set; }
    }

    public partial class RpiTemp
    {
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public double? Value { get; set; }

        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore)]
        public string Unit { get; set; }
    }

    public partial class PositionDisplay
    {
        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("house_number", NullValueHandling = NullValueHandling.Ignore)]
        public string HouseNumber { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("county")]
        public string County { get; set; }

        [JsonProperty("suburb")]
        public string Suburb { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("postcode")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Postcode { get; set; }

        [JsonProperty("country_code")]
        public string CountryCode { get; set; }

        [JsonProperty("residential", NullValueHandling = NullValueHandling.Ignore)]
        public string Residential { get; set; }

        [JsonProperty("road")]
        public string Road { get; set; }

        [JsonProperty("neighbourhood", NullValueHandling = NullValueHandling.Ignore)]
        public string Neighbourhood { get; set; }
    }

    public partial class TrackPosLoc
    {
        [JsonProperty("lat", NullValueHandling = NullValueHandling.Ignore)]
        public float? Lat { get; set; }

        [JsonProperty("lon", NullValueHandling = NullValueHandling.Ignore)]
        public float? Lon { get; set; }
    }

    public partial class AutoPi_Json
    {
        public static AutoPi_Json FromJson(string json) => JsonConvert.DeserializeObject<AutoPi_Json>(json, Helpers.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AutoPi_Json self) => JsonConvert.SerializeObject(self, Helpers.Converter.Settings);
    }

    //internal static class Converter
    //{
    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //    {
    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //        DateParseHandling = DateParseHandling.None,
    //        Converters =
    //        {
    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //        },
    //    };
    //}

    //internal class ParseStringConverter : JsonConverter
    //{
    //    public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

    //    public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    //    {
    //        if (reader.TokenType == JsonToken.Null) return null;
    //        var value = serializer.Deserialize<string>(reader);
    //        long l;
    //        if (Int64.TryParse(value, out l))
    //        {
    //            return l;
    //        }
    //        throw new Exception("Cannot unmarshal type long");
    //    }

    //    public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    //    {
    //        if (untypedValue == null)
    //        {
    //            serializer.Serialize(writer, null);
    //            return;
    //        }
    //        var value = (long)untypedValue;
    //        serializer.Serialize(writer, value.ToString());
    //        return;
    //    }

    //    public static readonly ParseStringConverter Singleton = new ParseStringConverter();




    //}

    //public static partial class JsonExtensions
    //{
    //    public static void ToNewlineDelimitedJson<T>(Stream stream, IEnumerable<T> items)
    //    {
    //        // Let caller dispose the underlying stream 
    //        using (var textWriter = new StreamWriter(stream, new UTF8Encoding(false, true), 1024, true))
    //        {
    //            ToNewlineDelimitedJson(textWriter, items);
    //        }
    //    }

    //    public static void ToNewlineDelimitedJson<T>(TextWriter textWriter, IEnumerable<T> items)
    //    {
    //        var serializer = JsonSerializer.CreateDefault();

    //        foreach (var item in items)
    //        {
    //            // Formatting.None is the default; I set it here for clarity.
    //            using (var writer = new JsonTextWriter(textWriter) { Formatting = Formatting.None, CloseOutput = false })
    //            {
    //                serializer.Serialize(writer, item);
    //            }
    //            // https://web.archive.org/web/20180513150745/http://specs.okfnlabs.org/ndjson/
    //            // Each JSON text MUST conform to the [RFC7159] standard and MUST be written to the stream followed by the newline character \n (0x0A). 
    //            // The newline charater MAY be preceeded by a carriage return \r (0x0D). The JSON texts MUST NOT contain newlines or carriage returns.
    //            textWriter.Write("\n");
    //        }
    //    }
    //}
}






