using System;
using System.Collections.Generic;
using System.Text;

namespace LiRACore.Models.RawData
{
    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using QuickLiRACore.Models.RawData.Trip;
    //
    //    var ttip = Ttip.FromJson(jsonString);


        using System;
        using System.Collections.Generic;
        using System.ComponentModel.DataAnnotations;
        using System.Globalization;
        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;

        public partial class Device
        {

           public Device()
            {
                Trips = new List<Trip>();
            }
            
            //public Guid LiRA_Device_Id { get; set; }
                   
            //VId
            public Guid DeviceId { get; set; }
                                               
            // Creation History
            public DateTimeOffset  Created_Date  { get; set; }

            // Last Update History
            public DateTimeOffset Updated_Date { get; set; }

            public ICollection<Trip> Trips { get; set; }


            public Guid FK_SourceType { get; set; }
            // navigation property 
            public SourceType SourceType { get; set; }
    }


        //public partial class Device
        //{
        //    public static Device FromJson(string json) => JsonConvert.DeserializeObject<Device>(json, QuickLiRACore.Models.RawData.Device.Converter.Settings);
        //}


  
    

}
