using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LiRAMap.Models
{
	//Class: Way
	//This class represents a Way (or Section) on the Map. It should be generated by the IWayProvider module in use.
	//The module may provide an extended class to enrich with additional data if wanted.
	public class Way
	{
		public ulong Id { get; set; }
		public string Name { get; set; }
		public IEnumerable<ulong> Nodes { get; set; }
	}
}
